# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=200, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=200, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
    ]
